name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove existing container (if running)
        run: |
          docker stop reactapp || true
          docker rm reactapp || true

      - name: Remove old image
        run: docker rmi my-image:v1 || true

      - name: Build Docker Image
        run: docker build -t my-image:v1 .

      - name: Run Container
        run: docker run -d -p 80:80 --name reactapp my-image:v1

      - name: Show Running Containers status
        run: docker ps
